FROM python:3.12.11-slim-buster


COPY /Binance_volatility_trading_bot/requirements-dash-UI.txt ./
RUN python -m pip install --upgrade pip\
  && pip install --no-cache-dir -r requirements-dash-UI.txt

WORKDIR /dash_UI
COPY /Binance_volatility_trading_bot/dash_UI/. ./dash_UI/

EXPOSE 8050
	
CMD ["python","dash_app.py"]