data_options:
  DB_CANDLE_FILE_NAME: candles.db
  DB_STUDY_FILE_NAME: study.db
  DB_TRANSACTIONS_FILE_NAME: transactions.db
  DB_TYPE: POSTGRES
  INIT_PERIOD: 201 hours ago UTC
  INIT_START: true
  INTERVAL: 1m
  POSTGRESS_DB: candles
  POSTGRESS_HOST: postgres_server
  POSTGRESS_PORT: 5432
  POSTGRES_PASS: postgres
  POSTGRES_USER: postgres
script_options:
  CLEAN_START: false
  DEBUG: true
  LOG_FILE: trades.txt
  LOG_TRADES: false
  MSG_TELEGRAM: true
  TEST_MODE: true
trading_options:
  CHANGE_IN_PRICE: 1
  COINS_MAX_VOLUME: 5000000000
  COINS_MIN_VOLUME: 100000000
  COOLOFF_MULTIPLIER_LOSS: 2
  COOLOFF_MULTIPLIER_SMALL_PROFIT: 1.5
  CUSTOM_LIST: false
  CUSTOM_LIST_AUTORELOAD: false
  FIATS:
  - EURUSDT
  - GBPUSDT
  - JPYUSDT
  - USDUSDT
  - DAIUSDT
  - AUDUSDT
  - BUSDUSDT
  - USDTVAI
  - USDTDAI
  - USDCUSDT
  - USTUSDT
  - USDTBVND
  - USDTBKRW
  - USDSUSDT
  - USDSBUSDT
  - PAXUSDT
  - BNBBULLUSDT
  - BNBBEARUSDT
  - BULLUSDT
  - BEARUSDT
  - ETHBULLUSDT
  - ETHBEARUSDT
  - EOSBULLUSDT
  - EOSBEARUSDT
  - XRPBULLUSDT
  - XRPBEARUSDT
  - 1INCHUPUSDT
  - AAVEUPUSDT
  - VENUSDT
  - XRPUPUSDT
  - LINKUPUSDT
  - DOTUPUSDT
  - UNIUPUSDT
  - FILUPUSDT
  - EOSUPUSDT
  - BNBUPUSDT
  - SUSHIUPUSDT
  - XLMUPUSDT
  - XTZUPUSDT
  - YFIUPUSDT
  - YFIDOWNUSDT
  MAX_PORTFOLIO_EXPOSURE: 10000
  MAX_PORTFOLIO_VALUE: 1000
  MIN_POSITIONS_CONCENTRATION: 3
  PAIR_WITH: USDC
  PERFORMANCE_RISK_THRESHOLD: -15
  RECHECK_INTERVAL: 4
  REINVEST_PROFITS: true
  SELL_ON_SIGNAL_ONLY: false
  SESSION_STOP_LOSS: -2
  SESSION_TAKE_PROFIT: 5
  SESSION_TPSL_OVERRIDE: false
  SIGNALLING_MODULES:
  - import_binance_tickers_coingecko
  - rs_wavetrend
  STOP_LOSS: 10
  TAKE_PROFIT: 2.0
  TICKERS_LIST: tickerlists/tickers_all.txt
  TIME_DIFFERENCE: 1
  TRADE_SLOTS: 10
  TRADE_TOTAL: 500
  TRADING_FEE: 0.075
  TRAILING_STOP_LOSS: 3
  TRAILING_TAKE_PROFIT: 1
  TRAILING_THRESHOLD: 0.8
  USE_TRAILING_STOP_LOSS: true
